apiVersion: v1
kind: Service
metadata:
  name: external-ip
spec:
  ports:
  - name: app
    port: 80
    protocol: TCP
    targetPort: 80 # External service port
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-ip
subsets:
- addresses:
  - ip: 192.168.1.1 # External service IP
  ports:
  - name: app
    port: 80 # External service port
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-service
  labels:
    kcert.dev/ingress: "managed"
spec:
  tls:
  - hosts:
    - external-service.example.org
    secretName: netdata-tls
  ingressClassName: nginx
  rules:
  - host: external-service.example.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: external-ip
            port:
              number: 80
